// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XSOBEL_SW_NEW_H
#define XSOBEL_SW_NEW_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xsobel_sw_new_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Ctrl_bus_BaseAddress;
} XSobel_sw_new_Config;
#endif

typedef struct {
    u32 Ctrl_bus_BaseAddress;
    u32 IsReady;
} XSobel_sw_new;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XSobel_sw_new_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XSobel_sw_new_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XSobel_sw_new_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XSobel_sw_new_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XSobel_sw_new_Initialize(XSobel_sw_new *InstancePtr, u16 DeviceId);
XSobel_sw_new_Config* XSobel_sw_new_LookupConfig(u16 DeviceId);
int XSobel_sw_new_CfgInitialize(XSobel_sw_new *InstancePtr, XSobel_sw_new_Config *ConfigPtr);
#else
int XSobel_sw_new_Initialize(XSobel_sw_new *InstancePtr, const char* InstanceName);
int XSobel_sw_new_Release(XSobel_sw_new *InstancePtr);
#endif

void XSobel_sw_new_Start(XSobel_sw_new *InstancePtr);
u32 XSobel_sw_new_IsDone(XSobel_sw_new *InstancePtr);
u32 XSobel_sw_new_IsIdle(XSobel_sw_new *InstancePtr);
u32 XSobel_sw_new_IsReady(XSobel_sw_new *InstancePtr);
void XSobel_sw_new_EnableAutoRestart(XSobel_sw_new *InstancePtr);
void XSobel_sw_new_DisableAutoRestart(XSobel_sw_new *InstancePtr);

void XSobel_sw_new_Set_input_r_r(XSobel_sw_new *InstancePtr, u32 Data);
u32 XSobel_sw_new_Get_input_r_r(XSobel_sw_new *InstancePtr);
void XSobel_sw_new_Set_output_r_r(XSobel_sw_new *InstancePtr, u32 Data);
u32 XSobel_sw_new_Get_output_r_r(XSobel_sw_new *InstancePtr);

void XSobel_sw_new_InterruptGlobalEnable(XSobel_sw_new *InstancePtr);
void XSobel_sw_new_InterruptGlobalDisable(XSobel_sw_new *InstancePtr);
void XSobel_sw_new_InterruptEnable(XSobel_sw_new *InstancePtr, u32 Mask);
void XSobel_sw_new_InterruptDisable(XSobel_sw_new *InstancePtr, u32 Mask);
void XSobel_sw_new_InterruptClear(XSobel_sw_new *InstancePtr, u32 Mask);
u32 XSobel_sw_new_InterruptGetEnabled(XSobel_sw_new *InstancePtr);
u32 XSobel_sw_new_InterruptGetStatus(XSobel_sw_new *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
