// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xsobel_sw_new.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XSobel_sw_new_CfgInitialize(XSobel_sw_new *InstancePtr, XSobel_sw_new_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Ctrl_bus_BaseAddress = ConfigPtr->Ctrl_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XSobel_sw_new_Start(XSobel_sw_new *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_sw_new_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XSOBEL_SW_NEW_CTRL_BUS_ADDR_AP_CTRL) & 0x80;
    XSobel_sw_new_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XSOBEL_SW_NEW_CTRL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XSobel_sw_new_IsDone(XSobel_sw_new *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_sw_new_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XSOBEL_SW_NEW_CTRL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XSobel_sw_new_IsIdle(XSobel_sw_new *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_sw_new_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XSOBEL_SW_NEW_CTRL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XSobel_sw_new_IsReady(XSobel_sw_new *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_sw_new_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XSOBEL_SW_NEW_CTRL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XSobel_sw_new_EnableAutoRestart(XSobel_sw_new *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_sw_new_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XSOBEL_SW_NEW_CTRL_BUS_ADDR_AP_CTRL, 0x80);
}

void XSobel_sw_new_DisableAutoRestart(XSobel_sw_new *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_sw_new_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XSOBEL_SW_NEW_CTRL_BUS_ADDR_AP_CTRL, 0);
}

void XSobel_sw_new_Set_input_r_r(XSobel_sw_new *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_sw_new_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XSOBEL_SW_NEW_CTRL_BUS_ADDR_INPUT_R_R_DATA, Data);
}

u32 XSobel_sw_new_Get_input_r_r(XSobel_sw_new *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_sw_new_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XSOBEL_SW_NEW_CTRL_BUS_ADDR_INPUT_R_R_DATA);
    return Data;
}

void XSobel_sw_new_Set_output_r_r(XSobel_sw_new *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_sw_new_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XSOBEL_SW_NEW_CTRL_BUS_ADDR_OUTPUT_R_R_DATA, Data);
}

u32 XSobel_sw_new_Get_output_r_r(XSobel_sw_new *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSobel_sw_new_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XSOBEL_SW_NEW_CTRL_BUS_ADDR_OUTPUT_R_R_DATA);
    return Data;
}

void XSobel_sw_new_InterruptGlobalEnable(XSobel_sw_new *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_sw_new_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XSOBEL_SW_NEW_CTRL_BUS_ADDR_GIE, 1);
}

void XSobel_sw_new_InterruptGlobalDisable(XSobel_sw_new *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_sw_new_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XSOBEL_SW_NEW_CTRL_BUS_ADDR_GIE, 0);
}

void XSobel_sw_new_InterruptEnable(XSobel_sw_new *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XSobel_sw_new_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XSOBEL_SW_NEW_CTRL_BUS_ADDR_IER);
    XSobel_sw_new_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XSOBEL_SW_NEW_CTRL_BUS_ADDR_IER, Register | Mask);
}

void XSobel_sw_new_InterruptDisable(XSobel_sw_new *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XSobel_sw_new_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XSOBEL_SW_NEW_CTRL_BUS_ADDR_IER);
    XSobel_sw_new_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XSOBEL_SW_NEW_CTRL_BUS_ADDR_IER, Register & (~Mask));
}

void XSobel_sw_new_InterruptClear(XSobel_sw_new *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSobel_sw_new_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XSOBEL_SW_NEW_CTRL_BUS_ADDR_ISR, Mask);
}

u32 XSobel_sw_new_InterruptGetEnabled(XSobel_sw_new *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSobel_sw_new_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XSOBEL_SW_NEW_CTRL_BUS_ADDR_IER);
}

u32 XSobel_sw_new_InterruptGetStatus(XSobel_sw_new *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSobel_sw_new_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XSOBEL_SW_NEW_CTRL_BUS_ADDR_ISR);
}

