#pragma line 1 "../sobel_sw_new.c" ::: 0
#pragma line 1 "../sobel_sw_new.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 149 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 10
#pragma line 289 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 63
#pragma line 427 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 190
#pragma line 6 "<command line>" 2 ::: 192
#pragma line 1 "<built-in>" 2 ::: 193
#pragma line 1 "../sobel_sw_new.c" 2 ::: 194
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 195
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 223
#pragma line 122 "/usr/include/features.h" 3 4 ::: 320
#pragma line 177 "/usr/include/features.h" 3 4 ::: 353
#pragma line 188 "/usr/include/features.h" 3 4 ::: 356
#pragma line 341 "/usr/include/features.h" 3 4 ::: 387
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 391
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 426
#pragma line 344 "/usr/include/features.h" 2 3 4 ::: 437
#pragma line 1 "/usr/include/sys/cdefs.h" 1 3 4 ::: 460
#pragma line 49 "/usr/include/sys/cdefs.h" 3 4 ::: 501
#pragma line 80 "/usr/include/sys/cdefs.h" 3 4 ::: 507
#pragma line 106 "/usr/include/sys/cdefs.h" 3 4 ::: 525
#pragma line 119 "/usr/include/sys/cdefs.h" 3 4 ::: 531
#pragma line 131 "/usr/include/sys/cdefs.h" 3 4 ::: 535
#pragma line 147 "/usr/include/sys/cdefs.h" 3 4 ::: 537
#pragma line 165 "/usr/include/sys/cdefs.h" 3 4 ::: 541
#pragma line 192 "/usr/include/sys/cdefs.h" 3 4 ::: 551
#pragma line 252 "/usr/include/sys/cdefs.h" 3 4 ::: 604
#pragma line 305 "/usr/include/sys/cdefs.h" 3 4 ::: 645
#pragma line 346 "/usr/include/sys/cdefs.h" 3 4 ::: 670
#pragma line 410 "/usr/include/sys/cdefs.h" 3 4 ::: 694
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 695
#pragma line 11 "/usr/include/bits/wordsize.h" 3 4 ::: 697
#pragma line 411 "/usr/include/sys/cdefs.h" 2 3 4 ::: 699
#pragma line 366 "/usr/include/features.h" 2 3 4 ::: 700
#pragma line 1 "/usr/include/gnu/stubs.h" 1 3 4 ::: 725
#pragma line 1 "/usr/include/gnu/stubs-64.h" 1 3 4 ::: 736
#pragma line 11 "/usr/include/gnu/stubs.h" 2 3 4 ::: 741
#pragma line 390 "/usr/include/features.h" 2 3 4 ::: 742
#pragma line 28 "/usr/include/stdio.h" 2 3 4 ::: 743
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 749
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 790
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 793
#pragma line 1 "/usr/include/bits/types.h" 1 3 4 ::: 795
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 823
#pragma line 11 "/usr/include/bits/wordsize.h" 3 4 ::: 825
#pragma line 28 "/usr/include/bits/types.h" 2 3 4 ::: 827
#pragma line 116 "/usr/include/bits/types.h" 3 4 ::: 888
#pragma line 1 "/usr/include/bits/typesizes.h" 1 3 4 ::: 895
#pragma line 26 "/usr/include/bits/typesizes.h" 3 4 ::: 913
#pragma line 76 "/usr/include/bits/typesizes.h" 3 4 ::: 918
#pragma line 122 "/usr/include/bits/types.h" 2 3 4 ::: 929
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 998
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 1012
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 1015
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1016
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1048
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1064
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1089
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1092
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1097
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1119
#pragma line 899 "/usr/include/wchar.h" 3 4 ::: 1140
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1143
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1154
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1164
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1166
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1170
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1219
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1220
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1226
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1228
#pragma line 177 "/usr/include/libio.h" 3 4 ::: 1252
#pragma line 245 "/usr/include/libio.h" 3 4 ::: 1263
#pragma line 293 "/usr/include/libio.h" 3 4 ::: 1304
#pragma line 302 "/usr/include/libio.h" 3 4 ::: 1306
#pragma line 334 "/usr/include/libio.h" 3 4 ::: 1328
#pragma line 390 "/usr/include/libio.h" 3 4 ::: 1354
#pragma line 434 "/usr/include/libio.h" 3 4 ::: 1358
#pragma line 464 "/usr/include/libio.h" 3 4 ::: 1373
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1385
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 1391
#pragma line 102 "/usr/include/stdio.h" 3 4 ::: 1393
#pragma line 119 "/usr/include/stdio.h" 3 4 ::: 1403
#pragma line 150 "/usr/include/stdio.h" 3 4 ::: 1425
#pragma line 1 "/usr/include/bits/stdio_lim.h" 1 3 4 ::: 1441
#pragma line 165 "/usr/include/stdio.h" 2 3 4 ::: 1458
#pragma line 208 "/usr/include/stdio.h" 3 4 ::: 1490
#pragma line 268 "/usr/include/stdio.h" 3 4 ::: 1536
#pragma line 305 "/usr/include/stdio.h" 3 4 ::: 1550
#pragma line 318 "/usr/include/stdio.h" 3 4 ::: 1553
#pragma line 411 "/usr/include/stdio.h" 3 4 ::: 1629
#pragma line 467 "/usr/include/stdio.h" 3 4 ::: 1668
#pragma line 527 "/usr/include/stdio.h" 3 4 ::: 1709
#pragma line 655 "/usr/include/stdio.h" 3 4 ::: 1822
#pragma line 731 "/usr/include/stdio.h" 3 4 ::: 1885
#pragma line 794 "/usr/include/stdio.h" 3 4 ::: 1934
#pragma line 825 "/usr/include/stdio.h" 3 4 ::: 1945
#pragma line 1 "/usr/include/bits/sys_errlist.h" 1 3 4 ::: 1975
#pragma line 854 "/usr/include/stdio.h" 2 3 4 ::: 2003
#pragma line 909 "/usr/include/stdio.h" 3 4 ::: 2035
#pragma line 930 "/usr/include/stdio.h" 3 4 ::: 2047
#pragma line 2 "../sobel_sw_new.c" 2 ::: 2050
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 2051
#pragma line 30 "/usr/include/math.h" 3 4 ::: 2073
#pragma line 1 "/usr/include/bits/math-vector.h" 1 3 4 ::: 2076
#pragma line 1 "/usr/include/bits/libm-simd-decl-stubs.h" 1 3 4 ::: 2102
#pragma line 26 "/usr/include/bits/math-vector.h" 2 3 4 ::: 2134
#pragma line 32 "/usr/include/math.h" 2 3 4 ::: 2135
#pragma line 1 "/usr/include/bits/huge_val.h" 1 3 4 ::: 2140
#pragma line 36 "/usr/include/math.h" 2 3 4 ::: 2165
#pragma line 1 "/usr/include/bits/huge_valf.h" 1 3 4 ::: 2167
#pragma line 38 "/usr/include/math.h" 2 3 4 ::: 2192
#pragma line 1 "/usr/include/bits/huge_vall.h" 1 3 4 ::: 2193
#pragma line 39 "/usr/include/math.h" 2 3 4 ::: 2212
#pragma line 1 "/usr/include/bits/inf.h" 1 3 4 ::: 2216
#pragma line 42 "/usr/include/math.h" 2 3 4 ::: 2240
#pragma line 1 "/usr/include/bits/nan.h" 1 3 4 ::: 2244
#pragma line 45 "/usr/include/math.h" 2 3 4 ::: 2269
#pragma line 1 "/usr/include/bits/mathdef.h" 1 3 4 ::: 2274
#pragma line 26 "/usr/include/bits/mathdef.h" 3 4 ::: 2291
#pragma line 41 "/usr/include/bits/mathdef.h" 3 4 ::: 2297
#pragma line 49 "/usr/include/math.h" 2 3 4 ::: 2304
#pragma line 82 "/usr/include/math.h" 3 4 ::: 2310
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 2311
#pragma line 87 "/usr/include/bits/mathcalls.h" 3 4 ::: 2388
#pragma line 127 "/usr/include/bits/mathcalls.h" 3 4 ::: 2418
#pragma line 378 "/usr/include/bits/mathcalls.h" 3 4 ::: 2657
#pragma line 83 "/usr/include/math.h" 2 3 4 ::: 2660
#pragma line 101 "/usr/include/math.h" 3 4 ::: 2671
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 2672
#pragma line 87 "/usr/include/bits/mathcalls.h" 3 4 ::: 2749
#pragma line 127 "/usr/include/bits/mathcalls.h" 3 4 ::: 2779
#pragma line 378 "/usr/include/bits/mathcalls.h" 3 4 ::: 3018
#pragma line 102 "/usr/include/math.h" 2 3 4 ::: 3021
#pragma line 135 "/usr/include/math.h" 3 4 ::: 3022
#pragma line 146 "/usr/include/math.h" 3 4 ::: 3025
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 3026
#pragma line 87 "/usr/include/bits/mathcalls.h" 3 4 ::: 3103
#pragma line 127 "/usr/include/bits/mathcalls.h" 3 4 ::: 3133
#pragma line 378 "/usr/include/bits/mathcalls.h" 3 4 ::: 3372
#pragma line 147 "/usr/include/math.h" 2 3 4 ::: 3375
#pragma line 161 "/usr/include/math.h" 3 4 ::: 3376
#pragma line 234 "/usr/include/math.h" 3 4 ::: 3439
#pragma line 246 "/usr/include/math.h" 3 4 ::: 3441
#pragma line 258 "/usr/include/math.h" 3 4 ::: 3443
#pragma line 274 "/usr/include/math.h" 3 4 ::: 3449
#pragma line 286 "/usr/include/math.h" 3 4 ::: 3451
#pragma line 314 "/usr/include/math.h" 3 4 ::: 3459
#pragma line 379 "/usr/include/math.h" 3 4 ::: 3513
#pragma line 396 "/usr/include/math.h" 3 4 ::: 3515
#pragma line 416 "/usr/include/math.h" 3 4 ::: 3519
#pragma line 438 "/usr/include/math.h" 3 4 ::: 3534
#pragma line 3 "../sobel_sw_new.c" 2 ::: 3590
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 3591
#pragma line 29 "/usr/include/string.h" 3 4 ::: 3612
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3617
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3642
#pragma line 33 "/usr/include/string.h" 2 3 4 ::: 3645
#pragma line 92 "/usr/include/string.h" 3 4 ::: 3682
#pragma line 124 "/usr/include/string.h" 3 4 ::: 3685
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 3722
#pragma line 160 "/usr/include/string.h" 2 3 4 ::: 3765
#pragma line 207 "/usr/include/string.h" 3 4 ::: 3787
#pragma line 231 "/usr/include/string.h" 3 4 ::: 3789
#pragma line 258 "/usr/include/string.h" 3 4 ::: 3794
#pragma line 278 "/usr/include/string.h" 3 4 ::: 3797
#pragma line 310 "/usr/include/string.h" 3 4 ::: 3807
#pragma line 337 "/usr/include/string.h" 3 4 ::: 3812
#pragma line 393 "/usr/include/string.h" 3 4 ::: 3833
#pragma line 439 "/usr/include/string.h" 3 4 ::: 3864
#pragma line 484 "/usr/include/string.h" 3 4 ::: 3887
#pragma line 512 "/usr/include/string.h" 3 4 ::: 3893
#pragma line 550 "/usr/include/string.h" 3 4 ::: 3917
#pragma line 4 "../sobel_sw_new.c" 2 ::: 3943
