#pragma line 1 "../sobel_sw_new.c" ::: -10
#pragma line 1 "../sobel_sw_new.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 0
#pragma line 289 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 53
#pragma line 427 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 180
#pragma line 6 "<command line>" 2 ::: 182
#pragma line 1 "<built-in>" 2 ::: 183
#pragma line 1 "../sobel_sw_new.c" 2 ::: 184
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 185
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 213
#pragma line 122 "/usr/include/features.h" 3 4 ::: 310
#pragma line 177 "/usr/include/features.h" 3 4 ::: 343
#pragma line 188 "/usr/include/features.h" 3 4 ::: 346
#pragma line 341 "/usr/include/features.h" 3 4 ::: 377
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 381
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 416
#pragma line 344 "/usr/include/features.h" 2 3 4 ::: 427
#pragma line 1 "/usr/include/sys/cdefs.h" 1 3 4 ::: 450
#pragma line 49 "/usr/include/sys/cdefs.h" 3 4 ::: 491
#pragma line 80 "/usr/include/sys/cdefs.h" 3 4 ::: 497
#pragma line 106 "/usr/include/sys/cdefs.h" 3 4 ::: 515
#pragma line 119 "/usr/include/sys/cdefs.h" 3 4 ::: 521
#pragma line 131 "/usr/include/sys/cdefs.h" 3 4 ::: 525
#pragma line 147 "/usr/include/sys/cdefs.h" 3 4 ::: 527
#pragma line 165 "/usr/include/sys/cdefs.h" 3 4 ::: 531
#pragma line 192 "/usr/include/sys/cdefs.h" 3 4 ::: 541
#pragma line 252 "/usr/include/sys/cdefs.h" 3 4 ::: 594
#pragma line 305 "/usr/include/sys/cdefs.h" 3 4 ::: 635
#pragma line 346 "/usr/include/sys/cdefs.h" 3 4 ::: 660
#pragma line 410 "/usr/include/sys/cdefs.h" 3 4 ::: 684
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 685
#pragma line 11 "/usr/include/bits/wordsize.h" 3 4 ::: 687
#pragma line 411 "/usr/include/sys/cdefs.h" 2 3 4 ::: 689
#pragma line 366 "/usr/include/features.h" 2 3 4 ::: 690
#pragma line 1 "/usr/include/gnu/stubs.h" 1 3 4 ::: 715
#pragma line 1 "/usr/include/gnu/stubs-64.h" 1 3 4 ::: 726
#pragma line 11 "/usr/include/gnu/stubs.h" 2 3 4 ::: 731
#pragma line 390 "/usr/include/features.h" 2 3 4 ::: 732
#pragma line 28 "/usr/include/stdio.h" 2 3 4 ::: 733
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 739
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 780
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 783
#pragma line 1 "/usr/include/bits/types.h" 1 3 4 ::: 785
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 813
#pragma line 11 "/usr/include/bits/wordsize.h" 3 4 ::: 815
#pragma line 28 "/usr/include/bits/types.h" 2 3 4 ::: 817
#pragma line 116 "/usr/include/bits/types.h" 3 4 ::: 878
#pragma line 1 "/usr/include/bits/typesizes.h" 1 3 4 ::: 885
#pragma line 26 "/usr/include/bits/typesizes.h" 3 4 ::: 903
#pragma line 76 "/usr/include/bits/typesizes.h" 3 4 ::: 908
#pragma line 122 "/usr/include/bits/types.h" 2 3 4 ::: 919
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 988
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 1002
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 1005
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1006
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1038
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1054
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1079
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1082
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1087
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1109
#pragma line 899 "/usr/include/wchar.h" 3 4 ::: 1130
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1133
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1144
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1154
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1156
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1160
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1209
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1210
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1216
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1218
#pragma line 177 "/usr/include/libio.h" 3 4 ::: 1242
#pragma line 245 "/usr/include/libio.h" 3 4 ::: 1253
#pragma line 293 "/usr/include/libio.h" 3 4 ::: 1294
#pragma line 302 "/usr/include/libio.h" 3 4 ::: 1296
#pragma line 334 "/usr/include/libio.h" 3 4 ::: 1318
#pragma line 390 "/usr/include/libio.h" 3 4 ::: 1344
#pragma line 434 "/usr/include/libio.h" 3 4 ::: 1348
#pragma line 464 "/usr/include/libio.h" 3 4 ::: 1363
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1375
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 1381
#pragma line 102 "/usr/include/stdio.h" 3 4 ::: 1383
#pragma line 119 "/usr/include/stdio.h" 3 4 ::: 1393
#pragma line 150 "/usr/include/stdio.h" 3 4 ::: 1415
#pragma line 1 "/usr/include/bits/stdio_lim.h" 1 3 4 ::: 1431
#pragma line 165 "/usr/include/stdio.h" 2 3 4 ::: 1448
#pragma line 208 "/usr/include/stdio.h" 3 4 ::: 1480
#pragma line 268 "/usr/include/stdio.h" 3 4 ::: 1526
#pragma line 305 "/usr/include/stdio.h" 3 4 ::: 1540
#pragma line 318 "/usr/include/stdio.h" 3 4 ::: 1543
#pragma line 411 "/usr/include/stdio.h" 3 4 ::: 1619
#pragma line 467 "/usr/include/stdio.h" 3 4 ::: 1658
#pragma line 527 "/usr/include/stdio.h" 3 4 ::: 1699
#pragma line 655 "/usr/include/stdio.h" 3 4 ::: 1812
#pragma line 731 "/usr/include/stdio.h" 3 4 ::: 1875
#pragma line 794 "/usr/include/stdio.h" 3 4 ::: 1924
#pragma line 825 "/usr/include/stdio.h" 3 4 ::: 1935
#pragma line 1 "/usr/include/bits/sys_errlist.h" 1 3 4 ::: 1965
#pragma line 854 "/usr/include/stdio.h" 2 3 4 ::: 1993
#pragma line 909 "/usr/include/stdio.h" 3 4 ::: 2025
#pragma line 930 "/usr/include/stdio.h" 3 4 ::: 2037
#pragma line 2 "../sobel_sw_new.c" 2 ::: 2040
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 2041
#pragma line 30 "/usr/include/math.h" 3 4 ::: 2063
#pragma line 1 "/usr/include/bits/math-vector.h" 1 3 4 ::: 2066
#pragma line 1 "/usr/include/bits/libm-simd-decl-stubs.h" 1 3 4 ::: 2092
#pragma line 26 "/usr/include/bits/math-vector.h" 2 3 4 ::: 2124
#pragma line 32 "/usr/include/math.h" 2 3 4 ::: 2125
#pragma line 1 "/usr/include/bits/huge_val.h" 1 3 4 ::: 2130
#pragma line 36 "/usr/include/math.h" 2 3 4 ::: 2155
#pragma line 1 "/usr/include/bits/huge_valf.h" 1 3 4 ::: 2157
#pragma line 38 "/usr/include/math.h" 2 3 4 ::: 2182
#pragma line 1 "/usr/include/bits/huge_vall.h" 1 3 4 ::: 2183
#pragma line 39 "/usr/include/math.h" 2 3 4 ::: 2202
#pragma line 1 "/usr/include/bits/inf.h" 1 3 4 ::: 2206
#pragma line 42 "/usr/include/math.h" 2 3 4 ::: 2230
#pragma line 1 "/usr/include/bits/nan.h" 1 3 4 ::: 2234
#pragma line 45 "/usr/include/math.h" 2 3 4 ::: 2259
#pragma line 1 "/usr/include/bits/mathdef.h" 1 3 4 ::: 2264
#pragma line 26 "/usr/include/bits/mathdef.h" 3 4 ::: 2281
#pragma line 41 "/usr/include/bits/mathdef.h" 3 4 ::: 2287
#pragma line 49 "/usr/include/math.h" 2 3 4 ::: 2294
#pragma line 82 "/usr/include/math.h" 3 4 ::: 2300
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 2301
#pragma line 87 "/usr/include/bits/mathcalls.h" 3 4 ::: 2378
#pragma line 127 "/usr/include/bits/mathcalls.h" 3 4 ::: 2408
#pragma line 378 "/usr/include/bits/mathcalls.h" 3 4 ::: 2647
#pragma line 83 "/usr/include/math.h" 2 3 4 ::: 2650
#pragma line 101 "/usr/include/math.h" 3 4 ::: 2661
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 2662
#pragma line 87 "/usr/include/bits/mathcalls.h" 3 4 ::: 2739
#pragma line 127 "/usr/include/bits/mathcalls.h" 3 4 ::: 2769
#pragma line 378 "/usr/include/bits/mathcalls.h" 3 4 ::: 3008
#pragma line 102 "/usr/include/math.h" 2 3 4 ::: 3011
#pragma line 135 "/usr/include/math.h" 3 4 ::: 3012
#pragma line 146 "/usr/include/math.h" 3 4 ::: 3015
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 3016
#pragma line 87 "/usr/include/bits/mathcalls.h" 3 4 ::: 3093
#pragma line 127 "/usr/include/bits/mathcalls.h" 3 4 ::: 3123
#pragma line 378 "/usr/include/bits/mathcalls.h" 3 4 ::: 3362
#pragma line 147 "/usr/include/math.h" 2 3 4 ::: 3365
#pragma line 161 "/usr/include/math.h" 3 4 ::: 3366
#pragma line 234 "/usr/include/math.h" 3 4 ::: 3429
#pragma line 246 "/usr/include/math.h" 3 4 ::: 3431
#pragma line 258 "/usr/include/math.h" 3 4 ::: 3433
#pragma line 274 "/usr/include/math.h" 3 4 ::: 3439
#pragma line 286 "/usr/include/math.h" 3 4 ::: 3441
#pragma line 314 "/usr/include/math.h" 3 4 ::: 3449
#pragma line 379 "/usr/include/math.h" 3 4 ::: 3503
#pragma line 396 "/usr/include/math.h" 3 4 ::: 3505
#pragma line 416 "/usr/include/math.h" 3 4 ::: 3509
#pragma line 438 "/usr/include/math.h" 3 4 ::: 3524
#pragma line 3 "../sobel_sw_new.c" 2 ::: 3580
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 3581
#pragma line 29 "/usr/include/string.h" 3 4 ::: 3602
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3607
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3632
#pragma line 33 "/usr/include/string.h" 2 3 4 ::: 3635
#pragma line 92 "/usr/include/string.h" 3 4 ::: 3672
#pragma line 124 "/usr/include/string.h" 3 4 ::: 3675
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 3712
#pragma line 160 "/usr/include/string.h" 2 3 4 ::: 3755
#pragma line 207 "/usr/include/string.h" 3 4 ::: 3777
#pragma line 231 "/usr/include/string.h" 3 4 ::: 3779
#pragma line 258 "/usr/include/string.h" 3 4 ::: 3784
#pragma line 278 "/usr/include/string.h" 3 4 ::: 3787
#pragma line 310 "/usr/include/string.h" 3 4 ::: 3797
#pragma line 337 "/usr/include/string.h" 3 4 ::: 3802
#pragma line 393 "/usr/include/string.h" 3 4 ::: 3823
#pragma line 439 "/usr/include/string.h" 3 4 ::: 3854
#pragma line 484 "/usr/include/string.h" 3 4 ::: 3877
#pragma line 512 "/usr/include/string.h" 3 4 ::: 3883
#pragma line 550 "/usr/include/string.h" 3 4 ::: 3907
#pragma line 4 "../sobel_sw_new.c" 2 ::: 3933
#pragma line 76 "../sobel_sw_new.c" ::: 4008
#pragma line 82 "../sobel_sw_new.c" ::: 4017
