// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xsobel_sw_new.h"

extern XSobel_sw_new_Config XSobel_sw_new_ConfigTable[];

XSobel_sw_new_Config *XSobel_sw_new_LookupConfig(u16 DeviceId) {
	XSobel_sw_new_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XSOBEL_SW_NEW_NUM_INSTANCES; Index++) {
		if (XSobel_sw_new_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XSobel_sw_new_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XSobel_sw_new_Initialize(XSobel_sw_new *InstancePtr, u16 DeviceId) {
	XSobel_sw_new_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XSobel_sw_new_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XSobel_sw_new_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

